# R Script - dplyr predominant
# Author: leerssej
# Date: Updated 28 Nov 2016
# Desc: Standardize Names with Regex expansion of abbreviations and acronyms
# Desc: Remove department & clinic level information
# Caveat: Known weakness - this is highly overfit to the CTMS data - towards erring on side of false negative 
# Caveat: instead of overzealous false positive actions.
# Caveat: non-REM country actions are commented out so as to allow swapping back into ENG and other regions.

options(stringsAsFactors = FALSE)
library(magrittr) 
library(tidyverse)

###### 93. REM2 data Regex ######
load("REM2subset")
glimpse(REM2subset)

CountrySum <- 
    select(REM2subset, ACCT_ID, rctGmCountry) %>% 
    group_by(rctGmCountry) %>% 
    summarise(n())
# View(CountrySum)
REM2subset2 <- mutate(REM2subset, swpCNTRBTR_ACCT_NAME = CNTRBTRACCTNAME)  #%>% #open pipe & select only to debug - run wide open afterwards
    # select(ORIGACCTNAME, CNTRBTRACCTNAME,swpCNTRBTR_ACCT_NAME, rctGmLocality, iso2LangCd)
#### REM2subset Subset
# strange characters removed
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\\"", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("C/O| - ", " ",. , ignore.case=T) 
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("-", " ",.) 
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("([a-z])'S", "\\1's", ., ignore.case = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("-", " ",.) 
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("_", " ",.) 
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\`", " ",.) 
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\?", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\B?", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("/", " ",.) 
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("/| - ", " ",.) 
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+'\\s+", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\(|\\)", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub(":", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub(";", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\\"", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("C/O| - ", " ",. , ignore.case=T) 
# Business entities
## Span? Euro?
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+(S|A)(\\s+)*C$", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+(S|A)(\\s+)*(S|A)$", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+S(\\s+)*A(\\s+)*(C(\\s+)*V)*$", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+S(\\s+)*(S\\s+)*A(\\s+)*(C(\\s+)*V)*\\s+", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)S(\\s+)*P(\\s+)*z(\\s+)*o(\\s+)*(o|z)(\\s+|$)", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+S(\\s)*r(\\s)*(l|o)(\\s+|$)", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)B(\\s+)*v(ba)*(\\s+|$)", " ", ., ignore.case=T)
### confounded letters that could get caught up and already have been butchered by the mdm cleaning box
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)S V(eta)* Marina(\\s+|$)", " Sveta Marina ", ., ignore.case=T)
## REM2 Business entities
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Pty( Limited)*(\\s+|$)", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)L(imi)*t(e)*d( Liability)*( Co(mpany|rporation)*)*($|\\s+)", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Co(mpany|rp(oration)*)*(\\s|$|-)", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Non-profit(\\s|$|-)", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)L(\\s)*P(\\s+|$)", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)P(\\s+)A(\\s+|$)", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Pp(\\s+|$)", " ",.) 
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Pc(-|\\s+|$)", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)D B A(\\s+|$)", " ",.) 
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Eood(\\s+|$)", " ",.) 
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Ood(\\s+|$)", " ",.) 
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Ooo(\\s+|$)", " ",.) 
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Vzw(\\s+|$)", " ",.) 
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Ad($)", " ",.) 
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Oyj*($)", " ",.) # FIN oy = Ltd, oyj = Corp
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Kft*($)", " ",.) # HUN kft = Ltd
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Hf($)", " ",.) # NOR: Helseforetak - Subisidary Health Enterprise
## Euro/FRA?
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+C\\s*V$", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Ag(\\s+|$)", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Ssa$", " ", ., ignore.case=T)
# Capitalization of articles fixed for names
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Y\\s+", " y ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Et\\s+"," et ",.)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+And\\s+"," and ",.)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<!Dr)\\s+U\\s+", " und ",. ,ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Und\\s+", " und ",. ,ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+E\\s+"," e ",.)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Em\\s+"," em ",.)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+En\\s+", " en ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Es\\s+", " es ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+De la\\s+", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+De l'", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+De I'", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Del(le)* ", " ", ., ignore.case=T,)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Degli\\s+", " ", ., ignore.case=T,)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+D(a|e|i|o|u)\\s+", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+D(a|e|o)s\\s+", " ", ., ignore.case=T) 
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Der\\s+", " der ",.) 
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Per\\s+", " per ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+of\\s+", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+L(e|a)\\s+", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+El\\s+", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("^Il\\s+", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+L'", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+D('|\\s+)", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+La\\s+", " la ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+For\\s+", " for ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Fue?r\\s+", " fur ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Per\\s+", " per ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+of\\s+", " of ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Ii(\\s+|$)", " II ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Iii(\\s+|$)", " III ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Viii(\\s+|$)", " VIII ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Xxiii(\\s+|$)", " XXIII ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Xxii(\\s+|$)", " XXII ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)First\\s+", " 1st ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Second\\s+", " 2nd ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Third\\s+", " 3rd ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Fourth\\s+", " 4th ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Fifth\\s+", " 5th ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Sixth\\s+", " 6th ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Seventh\\s+", " 7th ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Eighth\\s+", " 8th ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Ninth\\s+", " 9th ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Tenth\\s+", " 10th ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Icu(\\s+|$)", " ICU ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("M(\\s+)*d Anderson", " MD Anderson ", ., ignore.case=T)
# Abbreviations
## REM2 General
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Faculty\\s+(Of )*Medicine(\\s+|$)", " ", ., ignore.case=T)
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "bg" & !is.na(iso2LangCd), gsub("\\s+S\\s+V*\\s*", " Sveta ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+S\\s+(?=\\w+(a|e)(\\s+|$))", " Santa ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+S\\s+(?=\\w+(i|o)(\\s+|$))", " San ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Sta\\s+", " Santa ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Sv\\s+", " Sveta ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)St ", " Saint ",.)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Us ", " US ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)St\\s+", " Saint ",.) 
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)N(\\s+|$)", " North ", ., ignore.case=T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)So(\\s+|$)", " Southern ", ., ignore.case=T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Val(\\s+|$)", " Valley", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Cent(\\s+|$)", " Central ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Gen(\\s+|$)", " General ",.) 
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Rus(\\s+|$)", " Russian ",.) 
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Nj(\\s+|$)", " New Jersey ", .)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Wa(\\s+|$)", " Washington ", ., ignore.case=T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Dc(\\s+|$)", " DC ", ., ignore.case=T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Ri(\\s+|$)", " Rhode Island ", ., ignore.case=T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Ky(\\s+|$)", " Kentucky", ., ignore.case=T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Nc(\\s+|$)", " North Carolina ", ., ignore.case=T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)S Carolina(\\s+|$)", " South Carolina ", ., ignore.case=T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Tx(\\s|$)", " Texas ", ., ignore.case=T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Fl(\\s|$)", " Florida ", ., ignore.case=T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)S Texas(\\s|$)", " South Texas ", ., ignore.case=T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Southern Ca(\\s|$)", " Southern California ", ., ignore.case=T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)So Cal(ifornia)*(\\s|$)", " Southern California ", ., ignore.case=T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)S Florida(\\s|$)", " Southern Florida ", ., ignore.case=T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Sf(\\s|$)", " San Francisco ", .)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)S Francisco(\\s|$)", " San Francisco ", .)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)S San Fran(\\s|$)", " South San Francisco ", .)
## REM2 Hospital
### Most not gettting hits on the english, but better for growing
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Natl(\\s+|$)", " National ",.)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Canc(\\s+|$)", " Cancer ",.)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Comp Cancer(\\s+|$)", " Comprehensive Cancer ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Comprehensive Ca Care(\\s+|$)", " Comprehensive Cancer Care ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Trtmnt(\\s+|$)", " Treatment ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Serv(\\s+|$)", " Services ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Svcs(\\s+|$)", " Services ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Phys(\\s+|$)", " Physicians ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Pulm(\\s+|$)", " Pulmonary ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Crit(\\s+|$)", " Critical ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Priv(\\s+|$)", " Private ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Derma(\\s+|$)", " Dermatology ",.) 
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Allerg(\\s+|$)", " Allergy ",.) 
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Pulm(\\s+|$)", " Pulmonary ",.)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Aller\\s+Asth(\\s+|$)", " Allergy and Asthma ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Medi(\\s+|$)", " Medicine ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Mc(\\s+|$)", " Medical Center ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)HSC(\\s+|$)", " Health Sciences Center ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)C(\\s+)*c(\\s+)*c(\\s|$)", " Comprehensive Cancer Center (CCC) ", . ,ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Cntr($|\\s+)", " Center ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Cntrs($|\\s+)", " Centers ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Cr($|\\s+)", " Center ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Fac($|\\s+)", " Faculty ", ., ignore.case=T)
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "pl" & !is.na(iso2LangCd), gsub("(\\s+|^)Cent(\\s+|$)", " Centrum ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd %in% c("ja") & !is.na(iso2LangCd), gsub("(\\s+|^)Cent(\\s+|$)", " Center ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Uniw(\\s+|$)", " Uniwersytecki ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Specj(\\s+|$)", " Specjalistyczny ", ., ignore.case=T)
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd != "de" & !is.na(iso2LangCd), gsub("(\\s+|^)Klin(ik)*(\\s+|$)", " Kliniczny ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "pl" & !is.na(iso2LangCd), gsub("(\\s+|^)Spec(\\s+|$)", " Specjalistyczny ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "bg" & !is.na(iso2LangCd), gsub("(\\s+|^)Spec(\\s+|$)", " Specialized ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Sys(\\s+|$)", " System ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Conslts(\\s+|$)", " Consultants ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Cons(\\s+|$)", " Consultants ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)(Cancer\\s+Care|Blood|Medical)\\s+Spec(\\s+|$)", " \\2 Specialists ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Spec\\s+(clinic|Surgery)(\\s+|$)", " Specialty \\2 ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Dept*(\\s+|$)", " Department ",. ,ignore.case = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Afd(\\s+|$)", " Afdeling ",. ,ignore.case = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Div(\\s+|$)", " Division ",. ,ignore.case = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Rheum(\\s+|$)", " Rheumotology ",. ,ignore.case = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Comp(\\s+|$)", " Comprehensive ",. ,ignore.case = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)(for\\s+)*Oncol$", " Oncology",. ,ignore.case = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Ho*spt*(ia)*l*(\\s+|$)", " Hospital ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)MC(\\s+|$)", " Medical Center ", ., ignore.case=T)
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "bg" & !is.na(iso2LangCd), gsub("(\\s+|^)Bxl(\\s+|$)", " Bruxelles ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "ms" & !is.na(iso2LangCd), gsub("(\\s+|^)Nci(\\s+|$)", " Nilai Cancer Institute ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(!iso2LangCd == "ms" & !is.na(iso2LangCd), gsub("(\\s+|^)Nci(\\s+|$)", " National Cancer Institute ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "ru" & !is.na(iso2LangCd), gsub("(\\s+|^)Guz(\\s+|$)", " Public Health Agency [GUZ] ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "ru" & !is.na(iso2LangCd), gsub("(\\s+|^)Gbuz(\\s+|$)", " State Budgetary Healthcare Institution (SBHI [GBUZ]) ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "ru" & !is.na(iso2LangCd), gsub("(\\s+|^)Muz(\\s+|$)", " Municipal Health Agency [MUZ] ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "ru" & !is.na(iso2LangCd), gsub("(\\s+|^)Spb(\\s+|$)", " Saint Petersburg ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)S(ain)*t\\s*-*Peters*burg(\\s+|$)", " Saint Petersburg ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Saint-Petersburg(\\s+|$)", " Saint Petersburg ", ., ignore.case=T)
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "ru" & !is.na(iso2LangCd), gsub("(\\s+|^)Fsbsi(\\s+|$)", " Fsbi ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "ru" & !is.na(iso2LangCd), gsub("(\\s+|^)Mih(\\s+|$)", " Municipal Hospital ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "ru" & !is.na(iso2LangCd), gsub("(\\s+|^)Sbih(\\s+|$)", " Sbhi ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "ru" & !is.na(iso2LangCd), gsub("(\\s+|^)of Rf(\\s+|$)", " of Russian Federation ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "ru" & !is.na(iso2LangCd), gsub("(\\s+|^)Moh(\\s+|$)", " Ministry of Health ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
# Mispellings
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Comprhensive(\\s+|$)", " Comprehensive ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Clinc(\\s+|$)", " Clinic ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Medecine(\\s+|$)", " Medicine ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Ho*spt*(ia)*l*(\\s+|$)", " Hospital ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("Hosital*(\\s+|$)", "Hospital ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Hosiptal(\\s+|$)", "Hospital ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Hospitl(\\s+|$)", "Hospital ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Permantente(\\s+|$)", " Permanente ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Prefectual(\\s+|$)", " Prefectural ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Departmentof(\\s+|$)", " Department ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Nepprology(\\s+|$)", " Nephrology  ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Oncolgoy(\\s+|$)", " Oncology ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Pulmomary(\\s+|$)", " Pulmonary ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Hematologyandmed(\\s+|$)", " Hematology and Medical ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Massachu\\w+(\\s+|$)", " Massachusetts ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Oregan(\\s+|$)", " Oregon ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Uscf(\\s+|$)", " Ucsf ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Japanease(\\s+|$)", " Japanese ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Erasmuc(\\s+|$)", " Erasmus ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Faculity(\\s+|$)", " Faculty ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Tecnical(\\s+|$)", " Technical ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Univesity(\\s+|$)", " University ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Universi*tiy(\\s+|$)", " University ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Sity(\\s+|$)", " City ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Dispensar*y(\\s+|$)", " Dispensary ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Sceintific(\\s+|$)", " Scientific ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Militarty(\\s+|$)", " Military ", ., ignore.case=T)
# Finnish Translations
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Yliopistollinen Keskussairaala(\\s+|$)(?!\\[)", " Yliopistollinen Keskussairaala [University Central] ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Keskussairaala(\\s+|$)(?!\\[)", " Keskussairaala [Central Hospital] ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Sairaala(\\s+|$)(?!\\[)", " Sairaala [Hospital] ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Aluesairaala(\\s+|$)(?!\\[)", " Aluesairaala [Regional Hospital] ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Laakarikeskus(\\s+|$)", " Laakarikeskus [Medical Center] ", ., ignore.case=T)
# Hungarian Translations
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Megyei Korhaz(\\s+|$)", " Megyei Korhaz [County Hospital] ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Korhaza*(\\s+|$)(?!\\[)", " Korhaz [Hospital] ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Egyetem(\\s+|$)(?!\\[)", " Egyetem [University] ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Egeszsegugyi Kozpont(\\s+|$)(?!\\[)", " Egeszsegugyi Kozpont [Medical Center] ", ., ignore.case=T, perl = T)
# Swedish Translations
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Kliniska Provningar(\\s+|$)(?!\\[)", " Kliniska Provningar [Clinical Trials] ", ., ignore.case=T, perl = T)
# Translations from English into more common local standard terminology
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "nl" & !is.na(iso2LangCd), gsub("(\\s+|^)Medical Center(\\s+|$)", " Medisch Centrum ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "nl" & !is.na(iso2LangCd), gsub("(\\s+|^)Saint(\\s+|$)", " Sint ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "ro" & !is.na(iso2LangCd), gsub("(\\s+|^)County Clinical Emergency Hospital(\\s+|$)", " Spitalul Clinic (SC) Judetean Urgenta ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "ro" & !is.na(iso2LangCd), gsub("(\\s+|^)County Clinical Hospital(\\s+|$)", " Spitalul Clinic (SC) Judetean ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "ro" & !is.na(iso2LangCd), gsub("(\\s+|^)County Hospital(\\s+|$)", " Spitalul Judetean ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
# Translations from local standard terminology into English (mostly so I can yank these and nearby correlates out as stopwords or general non-desirables)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Nemocnicna Lekaren(\\s+|$)", " Hospital Pharmacy ", ., ignore.case=T, perl = T)

# Eastern Euro Abbrevs
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Szp(it)*(\\s+|$)", " Szpital ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Spit\\s+University(\\s+|$)", " Spitalul Universitar ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Scri(\\s+|$)", " Sarah Cannon Research Institute (SCRI) ", .)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)U(niversity)*\\s*M(ultiprofile)*(\\s+)*H(ospital)*(\\s+)*(for )*A(ctive)*(\\s+)*T(rea(t)*ment)*(\\s+|$)(?!\\()"," University Multiprofile Hospital for Active Treatment (UMHAT) ",., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)M(ultiprofile)*(\\s+)*H(ospital)*(\\s+)*(for )*A(ctive)*(\\s+)*T(rea(t)*ment)*(\\s+|$)(?!\\()"," Multiprofile Hospital for Active Treatment (MHAT) ",., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)S(pec)*(iali(z|s)ed)*(\\s+)*H(os)*(pital)*(\\s+)*(for)*(\\s+)*A(ctive)*(\\s+)*T(reatment)*(\\s+)*P(ediatrics)*(\\s+)*D((e|i)sease(s)*)*(\\s+|$)(?!\\()(?!Sv)"," Specialized Hospital for Active Treatment of Pediatric Diseases (SHATPD) ",., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)S(pec)*(iali(z|s)ed)*(\\s+)*H(os)*(pital)*(\\s+)*(for)*(\\s+)*A(ctive)*(\\s+)*T(reatment)*(\\s+)*O(ncological)*(\\s+)*D((e|i)sease(s)*)*(\\s+|$)(?!\\()(?!Sv)"," Specialized Hospital for Active Treatment of Oncological Diseases (SHATOD) ",., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)S(pec)*(iali(z|s)ed)*(\\s+)*H(os)*(pital)*(\\s+)*(for)*(\\s+)*A(ctive)*(\\s+)*T(reat)*(ment)*(\\s+)*O(ncolog)*(y|ical)*(\\s+)*D((e|i)sease(s)*)*(\\s+|$)(?!\\()(?!Sv)"," Specialized Hospital for Active Treatment of Oncological Diseases (SHATOD) ",., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)S(pec)*(iali(z|s)ed)*Ophth(almological)(\\s+)*H(os)*(pital)*(\\s+)*(for)*(\\s+)*A(ctive)*(\\s+)*T(reatment)*(\\s+)*O(phth)*(almological)*(\\s+)*D((e|i)sease(s)*)*(\\s+|$)(?!\\()(?!Sv)"," Specialized Ophthalmological Hospital for Active Treatment (SOHAT) ",., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)C(omp(lex|rehensive))*(\\s+)*O(ncolog(y|ical))*(\\s+)*C(enter)*(\\s+Coc)*(\\s+|$)(?!\\(C)"," Complex Oncology Center (COC) ",., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)D(iagnostic)*(\\s+)*C(onsult(ing|ati(ve|on)))*(\\s+)*C(enter)*(\\s+|$)(?!\\(D)"," Diagnostic Consulting Center (DCC) ",., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)C(entral)*(\\s+)*C(linical)*(\\s+)*B(ase)*(\\s+|$)(?!\\(C)"," Central Clinical Base (CCB) ",., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)C(enter)*\\s*(for)*(\\s+)*C(linical)*\\s*(and)*(\\s+)*B(asic)*\\s*R(esearch)*(\\s+|$)(?!\\(C)"," Center for Clinical and Basic Research (CCBR) ",., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)M(ilitary)*(\\s+)*M(edical)*(\\s+)*A(cademy)*(\\s+|$)(?!\\(M)"," Military Medical Academy (MMA) ",., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)C(ity)*(\\s+)*C(linic(al)*)*(\\s+)*H(ospital)*(\\s+|$)(?!\\(C)"," City Clinic Hospital (CCH) ",., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)R(eg)*(ional)*(\\s+)*C(linic(al)*)*\\s*P(sych)*(iatric)*\\s*H(ospital)*(\\s+|$)(?!\\(R)"," Regional Clinic Psychiatric Hospital (RCPH) ",., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)R(eg)*(ional)*(\\s+)*\\s*P(sych)*(iatric)*\\s*H(ospital)*(\\s+|$)(?!\\(R)"," Regional Psychiatric Hospital (RPH) ",., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)R(egional)*(\\s+)*C(linic(al)*)*\\s*P(sych)*(iatric)*\\s*H(ospital)*(\\s+|$)(?!\\(R)"," Regional Clinic Hospital (RCH) ",., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Hat(\\s+|$)(?!\\(H)"," Hospital for Active Treatment (HAT) ",., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)P(\\s+)*l(\\s+)*a(\\s+|$)"," PLA ",., ignore.case = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Hat(\\s+|$)(?!\\([MHS])"," Hospital for Active Treatment (HAT) ",., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)N(at(iona)*l)*(\\s+)*H(osp(ital)*)*(\\s+)*O(rg(anization)*)*(\\s+|$)(?!\\(N)"," National Hospital Organization (NHO) ",., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)N(iepubliczny)*(\\s+)*Z(aklad)*(\\s+)*O(pieki)*(\\s+)*Z(drowotnej)*(\\s+|$)(?!\\(N)", " NZOZ ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)S(amodzielny)*(\\s+)*P(ubliczny)*(\\s+)*S(zpital)*(\\s+)*K(liniczny)*(\\d+)*(\\s+|$)(?!\\(S)", " Samodzielny Publiczny Szpital Kliniczny (SPSK) \\9 ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Narodny\\s+Onkologicky\\s+Ustav(\\s+|$)(?!\\()", " Narodny Onkologicky Ustav (National Cancer Institute) ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Onkologicky\\s+Ustav(\\s+|$)(?!\\()", " Onkologicky Ustav (Cancer Institute) ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Clgandhsp(\\s+|$)", " College and Hospital ", ., ignore.case=T)
# Hungarian 
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)A(ltalanos)*\\s*O(rvostudomanyi)*\\s*K(ar)*\\s*(\\(*AOK\\)*)*(\\s+|$)", " Altalanos Orvostudomanyi Kar (AOK) ", ., ignore.case = T, perl = T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Univers\\w+(\\s+|$)", " University ", ., ignore.case=T)

# Pharmacy Garbage(not relevant for clustering/naming)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)(Clinical)*\\s*(Trials*)*\\s*(Department)*\\s*(of)*\\s*(Research)*\\s*(Oncology)*\\s*(Chemotherapy)*\\s*(Investigational)*\\s*(Drug)*\\s*(Research)*\\s*Pharmacy\\s*(Investigational)*\\s*(Drug)*\\s*(Research)*\\s*(Department)*\\s*(Clinical)*\\s*(Trials)*\\s*(Services)*\\s*(Associate)*\\s*(Lab)*(\\s+|$)", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Business and Distribution Center(\\s+|$)", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Apteka Szpitaln*a(\\s+|$)", " Szpital ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)^Apoteket Farmaci Ab Kliniska Provningar(\\s+|$)", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)^Apoteket Ab Kliniska Provningar(\\s+|$)", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)^Apoteket Ab Sjukhus(\\s+|$)", "Sjukhus ", ., ignore.case=T)
# Department
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)(Cardi(a|o)\\w+)*\\s*(Research(\\s+\\w)*)*\\s*(Out\\s*patients*)*\\s*(Radiation)*\\s*(Internal)*\\s*(Digestive)*\\s*(Organs)*\\s*(\\w+atrics*)*\\s*(\\w+(o|a)ry)*\\s*(\\w+logy)*\\s*(\\w+rapy)*\\s*Department(\\s+(of|for)\\s+)*(Family|General)*\\s*(Internal|Stomach)*\\s*(Medi\\w+)*\\s*(\\w+oma)*\\s*(and)*\\s*(\\w+atrics*)*\\s*(\\w+oma)*\\s*(Duodenum)*\\s*(\\w+ectal)*\\s*(\\w+(a|e)ry)*\\s*(Radia\\w+)*\\s*(\\w+ology)*\\s*(\\w+rapy)*\\s*(Clin\\w+)*\\s*(and)*\\s*(Res\\w+)*\\s*(Program)*\\s*(Family)*\\s*(Sleep|Nuclear)*\\s*(Medicine)*\\s*(Infectious|Coagulation)*\\s*(Diseases*)*\\s*(Disorders)*(\\s+|$)", " ",. ,ignore.case = T)
# Division
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Division\\s+(Of)*\\s*(\\w+iatric|Medic\\w+|\\w+ology|((General\\s+)*\\w+gery)|\\w+iatry|\\w+ary|Infect\\w+|Integrated)\\s*(and)*\\s*(\\w+iatric|Medicine|\\w+ology|\\w+ergy|\\w+iatry|Critical\\s+Care|Diseases*|Community)*\\s*(and)*\\s*(\\w+iatric|Medicine|\\w+ology|\\w+ergy|\\w+iatry|\\w+olism)*\\s*(Network)*(\\s+|$)", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\w+iatric|Medicine|\\w+ology|\\w+ergy|\\w+iatry|\\w+ary|Research|Trials|Renal)\\s*(and)*\\s*(\\w+iatric|Medicine|\\w+ology|\\w+ergy|\\w+iatry|Critical\\s+Care)*\\s*(and)*\\s*(\\w+iatric|Medicine|\\w+ology|\\w+ergy|\\w+iatry)*\\s+Division(\\s+|$)", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)(Klinische\\s)*(F|Ph)armac(i(a|e)|y)|(Ziekenhuis*Apotheek)( Central(e|izzata)*)*(\\s+|$)", " ", ., ignore.case=T)
## More useful in Addresses or Latin
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(F|Ph)armac(i(a|e)|y)\\s+(Department(\\s+|$))*(of )*", " ", ., ignore.case=T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub(" Servici(o|e)\\s+\\w+olog(i(a|e)|y)(\\s+Pediatric(a)*)*(\\S+\\w+olog(i(a|e)|y))*"," ",.)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("^Servici(o|e)\\s+\\w+olog(i(a|e)|y)(\\s+Pediatric(a)*)*"," ",.)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub(": (?<!(Onc))olog(i(a|e)|y)(\\s+Pediatric(a)*)*"," ",. ,perl = T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub(": (\\w+ology|Pharmacy|Department|Division(e)*)(\\s+\\w+)*"," " ,.)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)(Dip(artimento)*|Division(e)*|Sezione)( Scienze)*( Pediatriche)*( Adolescenza)*(Salute Mentale )*(\\w+ologia)*(-Clinic Trial Cen)*", " ",., ignore.case=T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+Dimed(\\s+|$)", " ", ., ignore.case=T)

# Floor
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\d+\\w+\\s+(and\\s+\\d+\\w+\\s+)*Floor", "", ., ignore.case=T)
# Celebrity Site Abbrevs 
# If back into ENG than there are number of potential celeb sites that didn't have expansion code upgrades(possibly)
## Canadian
# Start of Reconceived approach to Celebrity Sites
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd %in% c("af") & !is.na(iso2LangCd), gsub("(\\s+|^)Uct(\\s+|$)", " University of Capetown ", swpCNTRBTR_ACCT_NAME, ignore.case = T), swpCNTRBTR_ACCT_NAME))
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)B(ritish)*\\s*C(olumbia)*\\s*C(ancer)*\\s*A(gency)*\\s*(\\(*BCCA\\)*)*(\\s+|$)", " British Columbia Cancer Agency (BCCA) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)C(ent(re|er))*\\s*H(ospiti*ali(ar|ere*))*\\s*R(egional)*\\s*U(niversitaire)*\\s*(\\(*CHRU\\)*)*(\\s+|$)", " Centre Hospitalier Regional Universitaire (CHRU) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)C(ent(re|er))*\\s*H(ospiti*ali(ar|ere*))*\\s*R(egional)*\\s*(\\(*CHR\\)*)*(\\s+|$)", " Centre Hospitaliere Regional (CHR) ", ., ignore.case = T, perl = T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)C(ent(re|er))*\\s*H(ospiti*ali(ar|ere*))*\\s*U(niversitaire)*\\s*M(ontreal)*\\s*(\\(*CHUM\\)*)*(\\s+|$)", " Centre Hospitalier Universitaire Montreal (CHUM) ", ., ignore.case = T, perl = T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)C(ent(re|er))*\\s*H(ospiti*ali(ar|ere*))*\\s*U(niversitaire)*\\s*Q(uebec)*\\s*(\\(*CHUQ\\)*)*(\\s+|$)", " Centre Hospitalier Universitaire Quebec (CHUQ) ", ., ignore.case = T, perl = T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)C(ent(re|er))*\\s*H(ospiti*ali(ar|ere*))*\\s*U(niversitaire)*\\s*V(audois)*\\s*(\\(*CHUV\\)*)*(\\s+|$)", " Centre Hospitalier Universitaire Vaudois (CHUV) ", ., ignore.case = T, perl = T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)C(ent(re|er))*\\s*H(ospiti*ali(ar|ere*))*\\s*U(niversitaire)*\\s*S(herbrooke)*\\s*(\\(*CHUS\\)*)*(\\s+|$)", " Centre Hospitalier Universitaire Sherbrooke (CHUS) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)C(entre)*\\s*H(ospiti*ali(ar|ere*))*\\s*D(epartemental)*\\s*(\\(*CHD\\)*)*(\\s+|$)", " Centre Hospitalier Departemental (CHD) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)C(entre)*\\s*H(ospiti*ali(ar|ere*))*\\s*G(eneral)*\\s*(\\(*CHG\\)*)*(\\s+|$)", " Centre Hospitalier General (CHG) ", ., ignore.case = T, perl = T)
###### SecNum. ObjectFx ######
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)C(entre)*\\s*H(ospiti*ali(ar|ere*))*\\s*I(ntercommunal)*\\s*(\\(*CHI\\)*)*(\\s+|$)(?!Mei|Kharkiv|Tzu)", " Centre Hospitalier Intercommunal (CHI) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)C(entre)*\\s*H(ospiti*ali(ar|ere*))*\\s*S(pecialise)*\\s*(\\(*CHS\\)*)*(\\s+|$)", " Centre Hospitalier Specialise (CHS) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)C(ent(re|er))*\\s*H(ospiti*ali(ar|ere*))*\\s*U(niversitaire)*\\s+(\\w+)(\\s+|$)", " Centre Hospitalier Universitaire (CHU) \\7 ", ., ignore.case = T, perl = T)
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(!(iso2LangCd %in% c("pl","sk","uk")) & !is.na(iso2LangCd), gsub("(\\s+|^)C(ent(re|er))*\\s*H(ospiti*ali(ar|ere*))*(\\s+|$)(?!Depar|Gener|Inter|Speci|Unive|Regio)", " Centre Hospitalier (CH) ", swpCNTRBTR_ACCT_NAME, ignore.case = T, perl = T), swpCNTRBTR_ACCT_NAME))
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)N(orth)*\\s*S(hore)*\\s*L(ong)*\\s*I(sland)*\\s*J(ewish)*\\s*(\\(*NSLIJ\\)*)*(\\s+|$)", " North Shore Long Island Jewish (NSLIJ) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)J(apanese)*\\s*F(oundation)*\\s*(for)*\\s*C(ancer)*\\s*R(esearch)*(\\s+|$)(?!\\(J)", " Japanese Foundation for Cancer Research (JFCR) ", ., ignore.case=T, perl = T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)N(ational)*\\s*H(ealth)*\\s*S(ervice)*\\s*F(oundation)*\\s*T(rust)*\\s*(\\(*NHSFT\\)*)*(\\s+|$)", " National Health Service Foundation Trust (NHSFT) ", ., ignore.case = T, perl = T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)N(ottingham)*\\s*U(niversity)*\\s*H(ospitals)*\\s*N(ational)*\\s*H(ealth)*\\s*S(ervice)*\\s*F(oundation)*\\s*T(rust)*\\s*(\\(*NUH\\)*)*(\\s+|$)", " Nottingham University Hospitals (NUH) National Health Service Foundation Trust (NHSFT) ", ., ignore.case = T, perl = T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Q(ueen)*\\s*E(lizabeth)*\\s*I(I)*\\s*(\\(*QEII\\)*)*(\\s+|$)", " Queen Elizabeth II (QEII) ", ., ignore.case = T, perl = T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)S(an)*\\s*F(rancisco)*\\s*G(eneral)*\\s*H(ospital)*\\s*(\\(*SFGH\\)*)*(\\s+|$)", " San Francisco General Hospital (SFGH) ", ., ignore.case = T, perl = T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)U(niversity)*\\s*C(alifornia)*\\s*D(avis)*\\s*(\\(*UCD\\)*)*(\\s+|$)", " University of California Davis (UCD) ", ., ignore.case = T, perl = T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)U(niversity)*\\s*C(alifornia)*\\s*I(rvine)*\\s*(\\(*UCI\\)*)*(\\s+|$)", " University of California Irvine (UCI) ", ., ignore.case = T, perl = T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)U(niversity)*\\s*C(alifornia)*\\s*L(os)*\\s*A(ngeles)*\\s*(\\(*UCLA\\)*)*(\\s+|$)", " University of California Los Angeles (UCLA) ", ., ignore.case = T, perl = T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)U(niversity)*\\s*C(alifornia)*\\s*S(an)*\\s*D(iego)*\\s*(\\(*UCSD\\)*)*(\\s+|$)", " University of California San Diego (UCSD) ", ., ignore.case = T, perl = T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)U(niversity)*\\s*C(alifornia)*\\s*S(an)*\\s*F(rancisco)*\\s*(\\(*UCSF\\)*)*(\\s+|$)", " University of California San Francisco (UCSF) ", ., ignore.case = T, perl = T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)U(niversity)*\\s*M(edicine)*\\s*D(entistry)*\\s*N(ew)*\\s*J(ersey)*\\s*(\\(*UMDNJ\\)*)*(\\s+|$)", " University Medicine Dentistry New Jersey (UMDNJ) ", ., ignore.case = T, perl = T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=Montreal )(.*)M(assachusetts)*\\s*G(eneral)*\\s*H(ospital)*\\s*(\\(*MGH\\)*)*(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
# REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)M(assachusetts)*\\s*G(eneral)*\\s*H(ospital)*\\s*(\\(*MGH\\)*)*(\\s+|$)", " Massachusetts General Hospital (MGH) ", ., ignore.case = T, perl = T)

# Flemish Europe
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)M(edisch)*(\\s+)*C(entrum)*(\\s+)*A(lkmaar)*(\\s+|$)(?!\\(M)", " Medisch Centrum Alkmaar (MCA) ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)M(edisch)*(\\s+)*C(entrum)*(\\s+)*A(lkmaar)*(\\s+|$)(?!\\(M)", " Medisch Centrum Alkmaar (MCA) ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)A(cademisch)*(\\s+)*M(edisch)*(\\s+)*C(entrum)*(\\s+|$)(?!\\(A)", " Academisch Medisch Centrum (AMC) ", ., ignore.case=T, perl=T)
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "nl" & !is.na(iso2LangCd),gsub("(^|\\s+)N(etherlands)*(\\s+)*C(ancer)*(\\s+)*I(nstitute)*(\\s+|$)(?!\\(N)", " Netherlands Cancer Institute (NCI) ", swpCNTRBTR_ACCT_NAME, ignore.case = T, perl = T), swpCNTRBTR_ACCT_NAME))
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)O(nze)*(\\s+)*L(ieve)*(\\s+)*(\\(OL\\)\\s+)*V(rouwe)*(\\s+)*G(asthuis)*(\\s+|$)(?!\\(O)", " Onze Lieve (OL) Vrouwe Gasthuis (OLVG) ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)O(nze)*(\\s+)*L(ieve)*(\\s+)*(\\(OL\\)\\s+)*(\\s+|$)(?!\\(O)", " Onze Lieve (OL) ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)V(u)*(\\s+University)*(\\s+)*M(edi(sch|cal))*(\\s+)*C(ent(rum|er))*(\\s+Vumc)*(\\s+|$)(?!\\(V)", " Vrije Universiteit Medisch Centrum (VUmc) ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)U(niversitair)*(\\s+)*M(edisch)*(\\s+)*C(entrum)*(\\s+)*U(trecht)*(\\s+|$)(?!\\(U)", " Universitair Medisch Centrum Utrecht (UMCU) ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)U(niversitair)*(\\s+)*M(edisch)*(\\s+)*C(entrum)*\\s*G(roningen)*(\\s+|$)(?!\\(U)", " Universitair Medisch Centrum Groningen (UMCG) ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)U(niversitair)*(\\s+)*M(edisch)*(\\s+)*C(entrum)*\\s*N(ijmegen)*(\\s+|$)(?!\\(U)", " Universitair Medisch Centrum Nijmegen (UMCN) ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Radboudumc(\\s+|$)", " Universitair Medisch Centrum Nijmegen (UMCN) Saint Radboud ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)L(eiden)*(\\s+)*U(niversity)*(\\s+)*M(edical)*\\s*C(enter)*(\\s+|$)(?!\\(L)", " Leiden University Medical Center (LUMC) ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)U(niversitair)*(\\s+)*M(edisch)*(\\s+)*C(entrum)*(\\s+|$)(?![GLUN\\(])", " Universitair Medisch Centrum (UMC) ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)A(cad)*(emisc*h)*(\\s+)*Z(iekenhuis)*(\\s+)*M(aastricht)*(\\s*(AZM|Maastricht))*(\\s+|$)(?!\\(A)", " Academish Ziekenhuis Maastricht (AZM) ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Al*g*(emeen)*(\\s+)*Z(iekenhuis)*(\\s*(AZ))*(\\s+|$)", " Algemeen Ziekenhuis (AZ) ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)U(niversitaire*)*\\s*Z(iekenhuis)*\\s*B(russel)*\\s*(\\(*UZB\\)*)*(\\s+|$)", " Universitair Ziekenhuis Brussel (UZB) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)U(niversitaire*)*\\s*Z(iekenhuis)*\\s*L(euven)*\\s*(\\(*UZL\\)*)*(\\s+|$)", " Universitaire Ziekenhuis Leuven (UZL) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)U(niversitaire*)*\\s*Z(iekenhuis)*\\s*G(ent)*\\s*(\\(*UZG\\)*)*(\\s+|$)", " Universitaire Ziekenhuis Gent (UZG) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)U(niversitaire*)*\\s*Z(iekenhuis)*\\s*A(ntwerpen)*\\s*(\\(*UZA\\)*)*(\\s+|$)", " Universitaire Ziekenhuis Antwerpen (UZA) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)U(niversitaire*)*\\s*Z(iekenhuis)*(\\(*UZ\\)*)*(\\s+|$)(?![BLGA\\(])", " Universitaire Ziekenhuis Antwerpen (UZA) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)U\\s*Z\\s+Gasthuisberg(\\s+|$)", " Universitaire Ziekenhuis Leuven (UZL) Gasthuisberg", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Z(iekenhuis)*\\s*N(etwerk)*\\s*A(ntwerpen)*\\s*(\\(*ZNA\\)*)*(\\s+|$)", " Ziekenhuis Netwerk Antwerpen (ZNA) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Zk*hs*(\\s+|$)(?!\\()", " Ziekenhuis ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Zk*hs*(\\s+|$)", " Ziekenhuis ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)A Schweitzer(\\s+|$)", " Albert Schweitzer ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Alg CentrumZkhs*(\\s+|$)", "Algemeen Centrum Ziekenhuis ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)G(asthuis)*\\s*Z(usters)*\\s*A(ntwerpen)*\\s*(\\(*GZA\\)*)*(\\s+|$)", " GasthuisZusters Antwerpen (GZA) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Z(iekenhuis)*\\s*G(roep)*\\s*T(wente)*\\s*(\\(*ZGT\\)*)*(\\s+|$)", " Ziekenhuisgroep Twente (ZGT) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)A(lgemeen)*\\s*Z(iekenhuis)*\\s*(\\(*AZ\\)*)*(\\s+|$)", " Algemeen Ziekenhuis  (AZ) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)Ziekenhuis Ziekenhuis(\\s+|$)", " Ziekenhuis ", ., ignore.case = T, perl = T)

# Eastern Euro Sites
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)W(ojewodzki)*(\\s+)*S(zpital|pecjalistyczny)*(\\s+)*S(zpital|pecjalistyczny)*(\\s+|$)(?!\\(W)", " Wojewodzki Specjalistyczny Szpital (WSS) ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)W(ojewodzki)*(\\s+)*S(zpital)*(\\s+)*S(pecjalistyczny)*(\\s+|$)(?!\\(W)", " Wojewodzki Specjalistyczny Szpital (WSS) ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)F(akultna)*\\s*N(emocnica)*\\s*S()*\\s*P(oliklinikou)*\\s*(\\(*FNSP\\)*)*(\\s+|$)", " Fakultna Nemocnica S Poliklinikou (FNSP) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)N(emocnica)*\\s*S()*\\s*P(oliklinikou)*\\s*(\\(*NSP\\)*)*(\\s+|$)", " Nemocnica S Poliklinikou (NSP) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)F(akultna)*\\s*N(emocnica)*\\s*(\\(*FN\\)*)*(\\s+|$)", " Fakultna Nemocnica  (FN) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)U(niverzitna)*\\s*N(emocnica)*\\s*(\\(*\\)*)*(\\s+|$)", " Univerzitna Nemocnica (UN) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)C(ollegium)*(\\s+)*M(edicum)*(\\s+)*U(niwersytetu)*(\\s+)*J(agielonskiego)*(\\s+|$)(?!\\(C)", " Collegium Medicum Uniwersytetu Jagielonskiego (CMUJ) ", ., ignore.case=T, perl=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+)PTE($)", " ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)P(ecsi)*\\s*T(udomany)*E(gyetem)*\\s*(\\(*PTE\\)*)*(\\s+|$)", " Pecsi Tudomanyegyetem (PTE) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)C(entralny)*\\s*S(zpital)*\\s*K(liniczny)*\\s*(\\(*CSK\\)*)*(\\s+|$)(?!\\()", " Centralny Szpital Kliniczny (CSK) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)S(amodz)*(ielny)*\\s*P(ubli)*(czny)*\\s*S(zpital)*\\s*K(liniczny)*\\s*(\\(*SPSK\\)*)*(\\s+|$)", " Samodzielny Publiczny Szpital Kliniczny (SPSK) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)S(zpital)*\\s*K(liniczny)*\\s*(\\(*SK\\)*)*(\\s+|$)(?!\\()", " Szpital Kliniczny (SK) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)C(abinet)*\\s*M(edical)*\\s*I(ndividual)*\\s*(\\(*CMI\\)*)*(\\s+|$)", " Cabinet Medical Individual (CMI) ", ., ignore.case = T, perl = T)

# Russia & Ukraine
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)S(pitalul)*\\s*C(linic)*\\s*(\\(*SC\\)*)*(\\s+|$)", " Spitalul Clinic (SC) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)K(azan)*\\s*S(tate)*\\s*M(edical)*\\s*U(niversity)*\\s*(\\(*KSMU\\)*)*(\\s+|$)", " Kazan State Medical University (KSMU) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)R(egion)*(al)*\\s*C(l*inical)*\\s*H(ospital)*\\s*(\\(*RCH\\)*)*(\\s+|$)", " Regional Clinical Hospital (RCH) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)S(cientific)*\\s*R(esearch)*\\s*I(nstitute)*\\s*(\\(*SRI\\)*)*(\\s+|$)", " Scientific Research Institute (SRI) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)R(egional)*\\s*P(sychiatric)*\\s*H(ospital)*\\s*(\\(*RPH\\)*)*(\\s+|$)", " Regional Psychiatric Hospital (RPH) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)R(egional)*\\s*C(linical)*\\s*O(ncological)*\\s*D(ispensary)*\\s*(\\(*RCOD\\)*)*(\\s+|$)", " Regional Clinical Oncological Dispensary (RCOD) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)C(rimea)*\\s*S(tate)*\\s*M(edical)*\\s*U(niversity)*\\s*(\\(*CSMU\\)*)*(\\s+|$)", " Crimea State Medical University (CSMU) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)O(dessa)*\\s*S(tate)*\\s*M(edical)*\\s*U(niversity)*\\s*(\\(*OSMU\\)*)*(\\s+|$)", " Odessa State Medical University (OSMU) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)S(tate)*\\s*M(edical)*\\s*U(niversity)*(\\s+|$)(?!\\()", " State Medical University (SMU) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)C(ity)*\\s*C(linical)*\\s*H(ospital)*\\s*(\\(*CCH\\)*)*(\\s+|$)", " City Clinical Hospital (CCH) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)R(egional)*\\s*C(linical)*\\s*H(ospital)*\\s*(\\(*RCH\\)*)*(\\s+|$)", " Regional Clinical Hospital (RCH) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)R(eg)*(ional)* C(ommunal)*\\s*I(nstitution)*\\s*(\\(*RCI\\)*)*(\\s+|$)(?!\\()", " Regional Communal Institution (CI) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<!Dr)(\\s+|^)C(ommunal)*\\s*I(nstitution)*\\s*(\\(*CI\\)*)*(\\s+|$)(?!\\(|Par)", " Communal Institution (CI) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)N(ational)*\\s*M(edical)*\\s*U(niversity)*\\s*(\\(*NMU\\)*)*(\\s+|$)", " National Medical University (NMU) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)D(onetsk)*\\s*N(ational)*\\s*M(edical)*\\s*U(niversity)*\\s*(\\(*DNMU\\)*)*(\\s+|$)(?!\\()", " Donetsk National Medical University (DNMU) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)A(cademy)*\\s*(of\\s+)*M(edical)*\\s*S(ciences*)*\\s*(of\\s)*U(kraine)*\\s*(\\(*AMSU\\)*)*(\\s+|$)", " Academy of Medical Sciences of Ukraine (AMSU) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)R(egional)*\\s*C(linical)*\\s*P(sychiatric)*\\s*H(ospital)*\\s*(\\(*RCPH\\)*)*(\\s+|$)", " Regional Clinical Psychiatric Hospital (RCPH) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)P(sychiatric)*\\s*H(ospital)*\\s*(\\(*PH\\)*)*(\\s+|$)(?!\\()", " Psychiatric Hospital (PH) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)M(edical)*\\s*A(cademy)*\\s*(\\(*MA\\)*)*(\\s+|$)(?!\\()", " Medical Academy (MA) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)M(unicipal)*\\s*I(nstitution)*\\s*(\\(*MI\\)*)*(\\s+|$)", " Municipal Institution (MI) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)S(tate)*\\s*I(nstitution)*\\s*(Of)*\\s*H*(ealthcare)*\\s*(\\(*SHI\\)*)*(\\s+|$)", " State Institution Of Healthcare (SIH) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)S(tate)*\\s*E(ducational)*\\s*\\s*I(nstitution)*\\s*(\\(*SEI\\)*)*(\\s+|$)", " State Educational Institution (SEI) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("^S(tate)*\\s*I(nstitution)*\\s*(\\(*SI\\)*)*(\\s+|$)(?!\\()", " State Institution (SI) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)S(tate)*\\s*H(ealthcare)*\\s+I(nstitution)*\\s*(\\(*SHI\\)*)*(\\s+|$)(?!\\()", " State Healthcare Institution (SHI) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)N(on)*\\s*S(tate)*\\s*H(ealthcare)*\\s+I(nstitution)*\\s*(\\(N*SHI\\)*)*(\\s+|$)", " Non State Healthcare Institution (NSHI) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)S(tate)*\\s*B(udgetary)*\\s*E(ducational)*\\s*I(nstitution)*\\s*(\\(*SBEI\\)*)*(\\s+|$)", " State Budgetary Educational Institution (SBEI) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)S(tate)*\\s*B(udgetary)*\\s*H(ealthcare)*\\s*I(nstitution)*\\s*(\\(*SBHI\\)*)*(\\s+|$)(?!\\()", " State Budgetary Healthcare Institution (SBHI) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)F(ederal)*\\s*S(tate)*\\s*B(udgetary)*\\s*H(ealthcare)*\\s*I(nstitution)*\\s*(\\(*FSBHI\\)*)*(\\s+|$)(?!\\()", " Federal State Budgetary Healthcare Institution (FSBHI) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)F(ederal)*\\s*S(tate)*\\s*B(udgetary)*\\s*I(nstitution)*\\s*(of)*\\s*H(ealthcare)*(\\(*FSBIH\\)*)*(\\s+|$)(?!\\()", " Federal State Budgetary Institution of Healthcare (FSBIH) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)T(erritorial)*\\s*S(tate)*\\s*B(udgetary)*\\s*H(ealthcare)*\\s*I(nstitution)*\\s*(\\(*TSBHI\\)*)*(\\s+|$)(?!\\()", " Territorial State Budgetary Healthcare Institution (TSBHI) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)M(unicipal)*\\s*B(udget[ae]ry)*\\s*C(linical)*\\s*I(nstitution)*\\s*(Of)*\\s*H(ealthcare)*\\s*(\\(*MBCIOH\\)*)*(\\s+|$)", " Municipal Budgetary Clinical Institution of Healthcare (MBCIOH) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)S(tate)*\\s*B(udgetary)*\\s*I(nstitution)*\\s*(of)*\\s*H(ealthcare)*\\s*(\\(*SBIH\\)*)*(\\s+|$)", " State Budgetary Institution Of Healthcare (SBIH) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)F(ederal)*\\s*S(tate)*\\s*B(udgetary)*\\s*I(nstitution)*\\s*(\\(*FSBI\\)*)*(\\s+|$)", " Federal State Budgetary Institution (FSBI) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)F(ederal)*\\s*S(tate)*\\s*M(ilitary)*\\s*E(ducational)*\\s*I(nstitution)*\\s*(\\(*FSMEI\\)*)*(\\s+|$)", " Federal State Military Educational Institution (FSMEI) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)S(cientific)*\\s*R(esearch)*\\s*I(nstitute)*\\s*(\\(*SRI\\)*)*(\\s+|$)", " Scientific Research Institute (SRI) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)M(oscow)*\\s*S(tate)*\\s*M(edical)*\\s*U(niversity)*\\s*(\\(*M*SMU\\)*)*(\\s+|$)", " Moscow State Medical University (MSMU) ", ., ignore.case = T, perl = T)

# South Asia
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)A(ll)*\\s*I(ndia)*\\s*I(nstitute)*\\s*M(edical)*\\s*S(ciences)*\\s*(\\(*AIIMS\\)*)*(\\s+|$)", " All India Institute of Medical Sciences (AIIMS) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)K M C(\\s+|$)", "Kasturba Medical College (KMC) ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)H(ospital)*(\\s+)*U(niversit(y|i))*(\\s+)*K(ebangsaan)*(\\s+)*M(alaysia)*(\\s+|$)(?!\\(H)"," Hospital University Kebangsaan Malaysia (HUKM) ",., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)U(ni)*(versity)*(\\s+)M(alay(a|asia))*(\\s+)M(edical)*(\\s+)C(enter)*(\\s+|$)(?!\\(U)"," University Malaya Medical Center (UMMC) ",., ignore.case = T, perl = T)
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(iso2LangCd == "ms" & !is.na(iso2LangCd), gsub("(^|\\s+)N(ilai)*(\\s+)*C(ancer)*(\\s+)*I(nstitute)*(\\s+|$)(?!\\(N)", " Nilai Cancer Institute (NCI) ", swpCNTRBTR_ACCT_NAME, ignore.case = T, perl = T), swpCNTRBTR_ACCT_NAME))
# South Africa
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)G(lobal)*\\s*C(linical)*\\s*T(rials)*\\s*(\\(*GCT\\)*)*(\\s+|$)", " Global Clinical Trials (GCT) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)C(linical)*\\s*T(rial)*\\s*C(enter)*\\s*(\\(*CTC\\)*)*(\\s+|$)", " Clinical Trial Center (CTC) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)G(lobal)*\\s*V(ision)*\\s*I(nternational)*\\s*(\\(*GVI\\)*)*(\\s+|$)", " Global Vision International (GVI) ", ., ignore.case = T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(\\s+|^)U(niversity)*\\s*(of\\s+)*C(ape)*\\s*T(own)*\\s*(\\(*UCT\\)*)*(\\s+|$)", " University of Cape Town (UCT) ", ., ignore.case = T, perl = T)


#Hospital - pharmacy
## Flemish
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(.*)(?<=Ziekenhuis)(.*)\\s+Apotheek(\\s+|$)", "\\1 \\2", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(.*)(?<=Ziekenhuizen)(.*)\\s+Apotheek(\\s+|$)", "\\1 \\2", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("^Apotheek(.*)(?<=Ziekenhuis)(\\s+|$)", "\\1 \\2", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("^Apotheek(.*)(?<=Ziekenhuizen)(\\s+|$)", "\\1 \\2", ., ignore.case=T, perl = T)
## East Europe
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("^Apteka(.*)(?<=Szpital)(\\s+|$)", "\\1 \\2", ., ignore.case=T, perl = T)
## Northern Europe
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("^Apoteket(.*)(?<=Sygehus)(\\s+|$)", "\\1 \\2", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("^Apoteket\\s*ab(.*)*(?<=Sjukhus)(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=Sykehus)(.*)Apoteket(\\s+|$)", "\\1 \\2", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=Sjukhus)(.*)Apoteket(\\s+|$)", "\\1 \\2", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=Sjukehus)(.*)Apoteket(\\s+|$)", "\\1 \\2", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=Sygehus)(.*)Apoteket(\\s+|$)", "\\1 \\2", ., ignore.case=T, perl = T)

# Medical Center - Pharmacy
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("^Apotheek(.*)(?<=Medical\\sCenter)(\\s+|$)", "\\1 \\2", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("^Apotheek(.*)(?<=Medisch\\sCentrum)(\\s+|$)", "\\1 \\2", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(.*)(?<=Medisch\\sCentrum)(.*)\\s+Apotheek(\\s+|$)", "\\1 \\2", ., ignore.case=T, perl = T)

#Hospital - Cancer Center
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=Hospital)(.*)\\s+C(ancer)*\\s*C(enter)*(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=Hospital)(.*)\\s+C(linical)*\\s*T(rial)*\\s*N(etwork)*\\s*(and)*\\s*(Institute)*(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
#Hospital - Department
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=Hospital)(.*)\\s+(\\w+ology)*(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=Ziekenhuis)(.*)\\s+(\\w+ology)*(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=Ziekenhuis)(.*)\\s+(\\w+ology)*(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(.*)(?<=Hospital)(.*)\\s+Afdeling.*(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=Sygehus Vendsyssel Hjorring).*Afdeling(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=Sygehus LillebC&lt Vejle).*Afdeling(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(.*)(?<=Sygehus)(.*)\\s+Afdeling.*(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=Sygehus)(.*Afdeling)*(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(.*)\\s+Afdeling(.*)(?<=Hospital)(\\s+|$)", "\\2 ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(.*)(?<=Ziekenhuis)(.*)\\s+Afdeling.*(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(.*)(?<=Medical Center)(.*)\\s+Afdeling.*(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T) # Location (campus disappears but BusRules are to city level)
# Hospital - School of Medicine
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=Hospital)(.*)\\s+School\\s+(Of\\s+)*Medicine(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
# University - Pharmacy
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(.*)(?<=Universitair)(.*)\\s+Apotheek(\\s+|$)", "\\1 \\2", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("^Apteka(.*)(?<=Uniwersyteckie)(\\s+|$)", "\\1 \\2", ., ignore.case=T, perl = T)
#University - School of Medicine
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Faculty\\s+(Of )*Medic(ine|al)(\\s+|$)", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)Faculty\\s+(Of )*Medic(ine|al)(\\s+|$)", " ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(University|Tulane|Yale|Creighton|Angeles|Icahn|Mount\\s+Sinai)\\s+School\\s+(Of\\s+)*Medicine(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=University)(.*)\\s+School\\s+(Of\\s+)*Medicine(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=University)(.*)\\s+Medical\\s+(Of\\s+)*School(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=Universitesi)(.*)\\s+(Medical|Tip)\\s+Fa(c|k)ult(y|esi)(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
#University - Medical Center
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=University)(.*)\\s+Memorial\\s*M(edical)*\\s*C(enter)*(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=University)(.*)\\s*M(edical)*\\s*C(enter)*(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=Tulane)(.*?)\\s*H(ealth)*\\s*S(ciences)*\\s*C(enter)*(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
#University - Cancer Center
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=University)(.*)\\s+C(ancer)*\\s*C(enter|linic)*(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=University).*Institute*(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
#University - Hospital
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=University)(.*)\\s+Hospitals*(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=UNiversity)(.*)\\s+(\\w+ology)*(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
# UNiversity - Medical Faculty
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=University)(.*)\\s+Medic(al|ine)\\s+(Faculty|School|Facility)(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)
# UNiversity - University
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(^|\\s+)University\\s+University(\\s+|$)", " University ", ., ignore.case=T)
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("(?<=University)(.*)\\s+Medic(al|ine)\\s+(Faculty|School|Facility)(\\s+|$)", "\\1 ", ., ignore.case=T, perl = T)

# Eliminate the extraneous whiteSpace that later turns into separate values that get counted
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% trimws

# Add in city names to the generic Universitatsklinikum sites that folks are fond of adding in german speaking countries
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "University California", paste("University of California ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Regents University California", paste("University of California ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Hospital", paste("Hospital ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Regionshospital", paste("Regionshospitalet ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Sygehus", paste("Sygehus ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Apoteket Ab", paste("Apoteket ab ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Apoteket Farmaci Ab", paste("Apoteket ab ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "University Hospital", paste("University Hospital ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "University", paste("University ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Medical University", paste("Medical University ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "University Medical Center", paste("University Medical Center ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "University Hospital and Medical School", paste("University Hospital And Medical School ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Metropolitan Hospital", paste("Metropolitan Hospital ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Hospital Militar", paste("Hospital Militar ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "University Hospital", paste("University Hospital ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "University", paste("University ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Medical University", paste("Medical University ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "University Medical Center", paste("University Medical Center ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Academisch Medisch Centrum (AMC) ", paste("Academisch Medisch Centrum (AMC) ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "University Hospital and Medical School", paste("University Hospital And Medical School ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Multiprofile Hospital for Active Treatment (MHAT)", paste("Multiprofile Hospital for Active Treatment (MHAT) ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "National Multiprofile Hospital", paste("National Multiprofile Hospital ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "National Hospital In Oncology", paste("National Hospital in Oncology ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "National Specialized Hospital Oncology", paste("National Specialized Hospital in Oncology ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Fakultni Nemocnice", paste("Fakultni Nemocnice ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Fakultna Nemocnica", paste("Fakultna Nemocnica ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Faculty Hospital", paste("Faculty Hospital ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Specialistic Hospital", paste("Specialistic Hospital ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Szpital Specjalistyczny", paste("Szpital Specjalistyczny ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Szpital", paste("Szpital ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Spitalul Clinic (SC)", paste("Spitalul Clinic (SC) ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Regional Oncology Center", paste("Regional Oncology Center ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Regional Oncology Dispensary", paste("Regional Oncology Dispensary ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Regional Oncology Hospital", paste("Regional Oncology Hospital ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Regional Clinical Hospital (RCH)", paste("Regional Clinical Hospital (RCH) ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Institute Pathology", paste("Institute Pathology ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Rheumatology Private Practice", paste("Rheumatology Private Practice ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Private Practice", paste("Private Practice ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Practice", paste("Practice ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Wojewodzki Szpital Specjalistyczny", paste("Wojewodzki Szpital Specjalistyczny ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "NZOZ", paste("NZOZ ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "", paste(rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Health and Research Center", paste(" Health and Research Center ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Treatment Research Center", paste(" Treatment Research Center ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))
REM2subset2 %<>% mutate(swpCNTRBTR_ACCT_NAME = ifelse(swpCNTRBTR_ACCT_NAME == "Regional Cancer Center", paste(" Regional Cancer Center ", rctGmLocality, sep = ""), swpCNTRBTR_ACCT_NAME))

# Eliminate the extraneous whiteSpace that later turns into separate values that get counted
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% trimws
REM2subset2$swpCNTRBTR_ACCT_NAME %<>% gsub("\\s+", " ", ., ignore.case=T)


#Chkit
glimpse(REM2subset2)
###### 94. REM2 additional flags and columns from Regex ### ##
#Chkit 
# str(REM2subset2)

# Firewall against recalculating cleaning work
REM2subset3 <- REM2subset2
glimpse(REM2subset3)

#Build flags off of the original columns
REM2subset3 <-  mutate(REM2subset3, PvtPrac = 1*(grepl("(^|\\s+)Dr\\s+|(\\()*Priv(ate)* (Prac(tice)*|Clinic|(C|G)abinet|Office( of(\\s|$)*)*(\\))*)|(Medicine )*Prof(ession(al)*)* Corp(oration)*|\\s+(\\()*(Dr|Md|M D|Facp|Do|Pp|A C P)(\\s+|$)(\\()*", CNTRBTRACCTNAME, ignore.case = T)))
REM2subset3 <-  mutate(REM2subset3, CancerCtr = 1*(grepl("Can(cer)*|Onc|Onk", swpCNTRBTR_ACCT_NAME)))
REM2subset3 <-  mutate(REM2subset3, University = 1*(grepl("Universit", swpCNTRBTR_ACCT_NAME)))
REM2subset3 <-  mutate(REM2subset3, Pharmacy = 1*(grepl("Pharm|Apot|Aptek", CNTRBTRACCTNAME)))

# Turn the zero's to NA's
REM2subset3[REM2subset3 == 0] <- NA

##Analysis Table
# summarize the subcounts of flagged groups
REM2sumisnasTable <-  
    summarise(REM2subset3, 
              University = sum(!is.na(University)),
              CancerCtr = sum(!is.na(CancerCtr)), 
              PvtPrac = sum(!is.na(PvtPrac)), 
              Pharmacy = sum(!is.na(Pharmacy)), 
              Total = n()) %>% 
    mutate(pctUniversity = round(University/Total*100, digits = 1),
           pctCancerCtr = round(CancerCtr/Total*100, digits = 1),
           pctPvtPrac = round(PvtPrac/Total*100, digits = 1),
           pctPharmacy = round(Pharmacy/Total*100, digits = 1))
View(REM2sumisnasTable)

# Write&Save it
REM2fullData <- REM2subset3 
write.csv(REM2fullData, "REM2fullData.csv", na = "", row.names = F)
save(REM2fullData, file="REM2fullData")
